nodes:
  - name: "alpha"
    ip: "1.1.1.1"
    port: 22
    user: "user_a"
    id_file: "/home/my_user/.ssh/id_rsa"
  - name: "bravo"
    ip: "2.2.2.2"
    port: 8022
    user: "user_b"
    id_file: "/home/my_user/.ssh/id_rsa"

connectivity:
  icmp:
    - "1.1.1.1"
    - "2.2.2.2"
  tcp:
    - address: "1.1.1.1"
      port: 22
    - address: "2.2.2.2"
      port: 80
  http:
    - host: "https://google.com"
    - host: "https://mail.ru"

schedule:
  interval: "4h" # time between runs
  splitter: "5s" # time between checks for different nodes in one run